spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_shop
    username: root
    password: user#1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl