spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_shop
    username: root
    password: user#1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456789@

springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger